# Generated by Django 5.2.6 on 2025-09-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(choices=[('daily', 'Daily Commute'), ('family', 'Family Use'), ('luxury', 'Luxury'), ('sport', 'Sport/Performance'), ('offroad', 'Off-Road/Adventure')], max_length=20)),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('truck', 'Truck'), ('coupe', 'Coupe'), ('coupe', 'Coupe'), ('conertible', 'Convertible')], max_length=20)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='Comma-separated features')),
                ('image_Url', models.URLField(help_text='External image URL', max_length=500)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
